version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_dockerizing
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres123
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack
  api:
    container_name: api_dockerizing
    build: .
    ports:
      - 8080:8080
    restart: always
    volumes:
      - api_volume:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - fullstack
  # migrate:
  #   image: migrate/migrate:v4.15.2
  #   profiles: ["tools"]
  #   volumes:
  #     - ./migrations:/migrations
  #   entrypoint:
  #     [
  #       "migrate",
  #       "-path",
  #       "/migrations",
  #       "-database",
  #       "postgres://postgres:postgres123@postgres:5432/mangastore?sslmode=disable",
  #     ]
  #   command: ["up"]
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   restart: on-failure

volumes:
  database_dockerizing:
  api_volume:

networks:
  fullstack:
    driver: bridge
